---
# tasks file for logrotate

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags: logrotate

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  
- import_tasks: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
