---
# tasks file for logrotate

- name: logrotate gathering OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "main.yml"
      paths:
        - "defaults"
  tags: logrotate

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: suse.yml
  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'
