---
# tasks file for logrotate — Red Hat / Rocky / Alma / CentOS

- name: Install logrotate packages (dnf)
  become: true
  ansible.builtin.dnf:
    name: "{{ logrotate_packages }}"
    state: present
  register: register_install_package
  until: register_install_package is succeeded
  retries: 3
  tags: logrotate
