---
- name: Converge
  hosts: all
  become: true

  environment:
    TZ: "America/Chicago"
    DEBIAN_FRONTEND: "noninteractive"

  vars:
    logrotate_options:
      - weekly
      - su root adm
      - rotate 32
      - create
      - dateext
      - compress

    logrotate_applications:
      - name: mysql-backup
        definitions:
          - logs:
              - /var/backup/mysql/*.log
            options:
              - rotate 12
              - monthly
              - missingok
              - notifempty
              - compress
              - delaycompress

  tasks:
    - name: Include role realtime.logrotate
      ansible.builtin.include_role:
        name: realtime.logrotate
